# Generated by Django 5.0.4 on 2024-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='weight2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight5',
            field=models.TextField(null=True),
        ),
    ]
