# Generated by Django 5.0.4 on 2024-05-28 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_stock_alter_product_weight2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight5',
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField()),
                ('offer_price', models.TextField()),
                ('weight', models.TextField(null=True)),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
