# Generated by Django 5.0.4 on 2024-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cnf_password',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
