# Generated by Django 5.0.4 on 2024-06-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_users_cnf_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('fullname', models.TextField()),
                ('mobilenumber', models.TextField()),
                ('pincode', models.TextField()),
                ('add1', models.TextField()),
                ('add2', models.TextField()),
                ('landmark', models.TextField()),
                ('town', models.TextField()),
                ('state', models.TextField()),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
