# Generated by Django 5.0.4 on 2024-06-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address',
            new_name='addreses',
        ),
    ]
