# Generated by Django 5.0.4 on 2024-06-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_address_addreses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cnf_password',
        ),
    ]
