# Generated by Django 5.0.4 on 2024-06-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
