# Generated by Django 5.0.6 on 2024-06-26 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_weight_offer_price_alter_weight_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.TextField(null=True)),
                ('packed', models.TextField(null=True)),
                ('shipped', models.TextField(null=True)),
                ('outfordelivery', models.TextField(null=True)),
                ('delivered', models.TextField(null=True)),
                ('address_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addreses')),
                ('c_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart_item')),
            ],
        ),
    ]
