# Generated by Django 5.0.6 on 2024-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_orders_delivered_alter_orders_outfordelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expected_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateField(null=True),
        ),
    ]
