# Generated by Django 5.0.6 on 2024-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_orders_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
