# Generated by Django 5.0.6 on 2024-07-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_weight_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
