# Generated by Django 5.0.6 on 2024-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_orders_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='replacing_date',
            field=models.DateField(null=True),
        ),
    ]
