# Generated by Django 5.1.6 on 2025-04-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_orders_replacing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vector_data',
            field=models.TextField(null=True),
        ),
    ]
