# Generated by Django 5.1.6 on 2025-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_users_vector_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vector_data',
            field=models.TextField(null=True),
        ),
    ]
