# Generated by Django 5.1.6 on 2025-04-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order'),
        ('app', '0028_searchhistory'),
    ]

    operations = [
    ]
